apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scaffold
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: scaffold
        version: tradition.0.0
    spec:
      containers:
      - name: project
        image: reg.example.com/library/***:tradition.0.0
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/
          - name: runtime-volume
            mountPath: /data/site/web_pc/runtime
            readOnly: false
        resources:
          requests:
            memory: "100Mi"
            cpu: 500m
          limits:
            memory: "150Mi"
            cpu: "1"
      volumes:
      - name: nginx-config-volume
        configMap:
          name: project-nginx-config-volume
      - name: runtime-volume
        persistentVolumeClaim:
          claimName: scaffold-pvc
